### PR TITLE
Added new events for move, zoom, rotate, tilt

### PR DESCRIPTION
**Pull request by dkniffin**

### CODE REVIEW

**Comment by kekscom** [comment]
Should be easy detect drag events on integration side.
Sure we need extra events?
I would pled much more for a clean solution of map enter/leave in order to properly handle touch onmap/drag outside/release.
What do you think?

**Comment by dkniffin** [comment]
I'm fine dropping `drag`, `dragstart` and `dragend` from this, if you want. The only one I ended up using was `move`

**Comment by kekscom** [comment]
I see the case for move. What about zoom, rotation?
Perhaps a general 'change'?

**Comment by dkniffin** [comment]
Good idea. I'll add a `zoom`, `rotation`. It looks like there's already a `change` event. I'll add that to the docs

**Comment by kekscom** [comment]
Maybe 'change' is sufficient?
Should be properly documented anyway.

**Comment by dkniffin** [comment]
`change` gives no info about what was changed. In an effort to provide more info, and to make the event API more similar to leaflet, I vote for keeping them separate.

**Comment by kekscom** [comment]
Convinces me.

**Comment by dkniffin** [comment]
Alright, I added those. The other one I could add is `bend`. I'm not really sure what the bend option is for, though.

**Comment by kekscom** [comment]
bend was planned for Inception rendering mode.
Just ignore it.

**Pull request merged**
