### PR TITLE
Fixed getBounds

### LINKED ISSUE #67: Fix map.getBounds()
It looks like [getBounds()](https://github.com/OSMBuildings/OSMBuildings/blob/e1e2d694337b07210824a5cca2a41548ace6d493/src/engines/Basemap/index.js#L161) was disabled a while back, due to issues with camera tilt. I'd like to use that function for something I'm doing. Can we fix it?

### PR DESCRIPTION
**Pull request by dkniffin**
(Note: this does not resolve #67. See discussion below.)

### CODE REVIEW

**Comment by rbuch703** [comment]
Wouldn't this return the wrong results if the map is rotated?

**Comment by dkniffin** [comment]
It seemed to return the right thing. I was showing the bounding "box" on a map, and it looked right.

**Comment by rbuch703** [comment]
Well, yes, it returns the correct points, but the point names don't fit. If I understand the code correctly, your `ne` will return the lat/lon pair of the *top-left* screen corner. But if you rotate the map - e.g. by 180 degrees -  that top-left corner will display the south-west-most part of your map, which you still return as `ne`.

In the end, we'll probably want to provide two distinct methods: one should just return an array of the world positions of the four view corners, in clockwise or counter-clockwise order. That's essentially what you did, but returning an array of points solved the problem of misleading member names. The second method should keep the old interface and return the north-most and south-most latitudes, and the west-most and east-most longitudes displayed. I implemented that in c8d77dd on the `develop` branch, but have not yet tested it much.

**Comment by dkniffin** [comment]
Ah, I see what you're saying. That makes sense. Let me update to reflect that.

**Comment by kekscom** [comment]
I lost track a bit on this topic.
Why would we need both getBounds() and getCameraBounds()?
If possible let's keep it less code and methods.

For function interface, I don't mind to break it. We'll reflect that in versioning.

**Comment by dkniffin** [comment]
So, my version of this method (now called `getCameraBounds`) returns an array of points, that make a geometry like this: 
image

The other version of this method (`getBounds`) returns an object with `n`, `s`, `e`, and `w` as keys, and the values correspond to the lat/lon extents of the camera. I believe `getBounds()` is essentially a bounding _box_ around `getCameraBounds()`, in the form of an object.

**Comment by kekscom** [comment]
Ok this is what I thought.
Would you mind to just repurpose getBounds() with your method?

**Comment by dkniffin** [comment]
@kekscom I could do that, but I'm worried it would confuse developers who use the method, because it's different from [leaflet's getBounds](http://leafletjs.com/reference.html#map-getbounds)

**Comment by kekscom** [comment]
I see. Personally I don't need an exact replication of Leaflets API.
But if you like, go for n,e,s,w properties or sort Lat/Lon and return ne,sw or the like.

**Comment by rbuch703** [comment]
To fix issue #67, I already reimplemented the old `getBounds()` returning n/e/s/w. I think both methods may be useful to developers as they do different things. We just need to explain the differences in the documentation.

**Comment by rbuch703** [comment]
One thing that we should discus for `getCameraBounds()` is what it should return for the top-left and top-right corner if the horizon is visible. Currently, I think it will just set them to `undefined`. Now, this is technically correct (the camera "bounds" are unbounded in this case), but it may or may not be practically useful for developers.

**Comment by dkniffin** [comment]
@rbuch703 Ah yea. A literal edge case :P What do you think we should return for that?

**Comment by kekscom** [comment]
I for undefined too. The only thought is, what would you need the method for?
Perhaps drawing the result on a 2D map like @dkniffin just did or perhaps load tiles up to distance d.
With undefined, you have no idea what the opening angle up to d is.

Still need to check both methods :-)

**Comment by rbuch703** [comment]
Yeah, returning `undefined` is probably fine, since we don't have an actual use case to determine what to return instead. One option would be to return the view quad, transformed to the lat/lon coordinate system - since the view quad is already clamped to the maximum render distance in those cases. But again, we don't know yet if that would actually be useful for anybody.

**Comment by dkniffin** [comment]
As soon as we get this merged, I've got a minimap example working that I'll push up and make a PR out of.

image

**Comment by kekscom** [comment]
Hey.. Nice to see this for OSM Buildings!

**Comment by kekscom** [comment]
Alright, I merged and finally I got what the difference is.
For `getBounds()` as it is I don't really see a use case. The results could even be derived from `getCameraBounds()`.

What I'd love to have:

- result of getCameraBounds(), but in getBounds()
- drop getCameraBounds name
- currently getCameraBounds has a dependency on osmb. Either make it a osmb method or remove the dependency.

**Comment by kekscom** [comment]
Alright, I just did the changes. Hope you're both ok with it.

**Comment by rbuch703** [comment]
Fine by me.

**Comment by dkniffin** [comment]
@kekscom is that change on master? I don't see it.

Also, I've been thinking. Is there a reason that you're keeping the interface for `map` separate from `osmb`? It's a little confusing to figure out which one I need to use for certain methods. ie: If I want to add a listener, do I put it on the osmb, or the map? answer: it depends what I'm doing. It'd be nice to just have one object to interact with. Or, maybe it's just naming that needs to be updated. Perhaps `OSMBuildings` would be better named `BuildingLayer`? Just spitballing here.

**Comment by kekscom** [comment]
Yes, it's on master now.

**Pull request merged**
