### PR TITLE
Another attempt at getting dist builds working, for bower

### PR DESCRIPTION
**Pull request by dkniffin**
Hopefully this one works. If it doesn't, it should at least provide more info in the travis build.

### CODE REVIEW

**Comment by dkniffin** [comment]
@kekscom Hmm, this still didn't work, and I'm not sure why. [It looks like](https://travis-ci.org/OSMBuildings/OSMBuildings/builds/124591525#L336) it should have worked, but it didn't. After that build ran, I tried running all the commands locally, and it worked perfectly, as you can see [here](https://github.com/OSMBuildings/OSMBuildings/commit/680fca897b3743d80b2a717f2c1ad13aeab17600). Any ideas why it wouldn't be working from Travis?

**Comment by kekscom** [comment]
But here it seems to have worked: https://github.com/OSMBuildings/OSMBuildings/tree/master/dist/OSMBuildings

**Comment by dkniffin** [comment]
Yea, that was my manual attempt. I may have a lead, though. [It looks like travis puts git in a detached head state](https://travis-ci.org/OSMBuildings/OSMBuildings/builds/124591525#L117). Just gotta figure out the right way to get it to the right state. Is it alright if I push to master a few times, so I don't have to open PRs for each of my debugging steps on this?

**Comment by kekscom** [comment]
Still considering to just un-ignore the ist files. But we have to agree on it.
However, yes please try without PRs.

**Comment by dkniffin** [comment]
I don't think we should un-ignore it, because then we're at risk of getting PRs that include builds.

**Comment by kekscom** [comment]
I see. Just wanted to make this easier.

**Comment by dkniffin** [comment]
@kekscom Alright, the last push I made fixed the issue, but I've got a kind of interesting problem now. My commit (3e08ec849a587d07277188128c33352073e5cf12), kicked off a travis build (88), which pushed a new commit (88df06d0af3af579a6ea8551225b6ee510c94b4c). That kicked off another travis build (89) which seems to have failed.

**Comment by kekscom** [comment]
Well it builds on repo change...

**Comment by dkniffin** [comment]
[Found a fix](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build)

**Comment by dkniffin** [comment]
@kekscom Alright, I think we're good on the dist build process now. 🎉

**Comment by dkniffin** [comment]
Oh, and with this, we may want to make a new release, because I don't think bower will work until we do.

**Comment by kekscom** [comment]
New release in terms of new version number or just building it all?

**Comment by dkniffin** [comment]
Version bump

**Comment by kekscom** [comment]
Done.
If this works.. awesome!

**Comment by dkniffin** [comment]
It works! 👍

**Comment by kekscom** [comment]
BAM! :-)

**Pull request merged**
